-- Salas / recursos físicos
CREATE TABLE sala (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(64),
    nombre VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO tipo_catalogo (codigo, nombre, descripcion, activo)
SELECT 'TIPO_CITA', 'Tipo de consulta', 'Clasificación de la cita (primera vez, control, etc.)', TRUE
WHERE NOT EXISTS (SELECT 1 FROM tipo_catalogo WHERE codigo = 'TIPO_CITA');

INSERT INTO catalogo (tipo_catalogo_id, codigo, nombre, orden, activo)
SELECT t.id, 'PRIMERA_VEZ', 'Primera vez', 1, TRUE
FROM tipo_catalogo t WHERE t.codigo = 'TIPO_CITA'
  AND NOT EXISTS (SELECT 1 FROM catalogo c WHERE c.tipo_catalogo_id = t.id AND c.codigo = 'PRIMERA_VEZ');

INSERT INTO catalogo (tipo_catalogo_id, codigo, nombre, orden, activo)
SELECT t.id, 'CONTROL', 'Control / seguimiento', 2, TRUE
FROM tipo_catalogo t WHERE t.codigo = 'TIPO_CITA'
  AND NOT EXISTS (SELECT 1 FROM catalogo c WHERE c.tipo_catalogo_id = t.id AND c.codigo = 'CONTROL');

INSERT INTO catalogo (tipo_catalogo_id, codigo, nombre, orden, activo)
SELECT t.id, 'PROCEDIMIENTO', 'Procedimiento', 3, TRUE
FROM tipo_catalogo t WHERE t.codigo = 'TIPO_CITA'
  AND NOT EXISTS (SELECT 1 FROM catalogo c WHERE c.tipo_catalogo_id = t.id AND c.codigo = 'PROCEDIMIENTO');

CREATE TABLE tipo_cita_regla (
    catalogo_id BIGINT NOT NULL PRIMARY KEY REFERENCES catalogo (id) ON DELETE CASCADE,
    duracion_minutos INT NOT NULL DEFAULT 45,
    buffer_antes_minutos INT NOT NULL DEFAULT 0,
    buffer_despues_minutos INT NOT NULL DEFAULT 0
);

INSERT INTO tipo_cita_regla (catalogo_id, duracion_minutos, buffer_antes_minutos, buffer_despues_minutos)
SELECT c.id, 60, 5, 10 FROM catalogo c JOIN tipo_catalogo t ON c.tipo_catalogo_id = t.id
WHERE t.codigo = 'TIPO_CITA' AND c.codigo = 'PRIMERA_VEZ';

INSERT INTO tipo_cita_regla (catalogo_id, duracion_minutos, buffer_antes_minutos, buffer_despues_minutos)
SELECT c.id, 30, 0, 5 FROM catalogo c JOIN tipo_catalogo t ON c.tipo_catalogo_id = t.id
WHERE t.codigo = 'TIPO_CITA' AND c.codigo = 'CONTROL';

INSERT INTO tipo_cita_regla (catalogo_id, duracion_minutos, buffer_antes_minutos, buffer_despues_minutos)
SELECT c.id, 90, 10, 15 FROM catalogo c JOIN tipo_catalogo t ON c.tipo_catalogo_id = t.id
WHERE t.codigo = 'TIPO_CITA' AND c.codigo = 'PROCEDIMIENTO';

INSERT INTO sala (codigo, nombre, activo) VALUES ('CONS1', 'Consultorio 1', TRUE);
INSERT INTO sala (codigo, nombre, activo) VALUES ('SALA_RX', 'Sala rayos X', TRUE);

ALTER TABLE cita ADD COLUMN tipo_cita_catalogo_id BIGINT REFERENCES catalogo (id);
ALTER TABLE cita ADD COLUMN sala_id BIGINT REFERENCES sala (id);
ALTER TABLE cita ADD COLUMN motivo_texto VARCHAR(500);
ALTER TABLE cita ADD COLUMN origen VARCHAR(40) NOT NULL DEFAULT 'INTERNO';
ALTER TABLE cita ADD COLUMN created_by_user_id BIGINT REFERENCES app_user (id);
ALTER TABLE cita ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE cita ADD COLUMN updated_by_user_id BIGINT REFERENCES app_user (id);
ALTER TABLE cita ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE cita ADD COLUMN cancelled_by_user_id BIGINT REFERENCES app_user (id);
ALTER TABLE cita ADD COLUMN cancel_reason VARCHAR(500);
ALTER TABLE cita ADD COLUMN inasistencia_marcada_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE cita ADD COLUMN inasistencia_marcada_by_user_id BIGINT REFERENCES app_user (id);

CREATE INDEX idx_cita_sala_inicio ON cita (sala_id, inicio_ts);

CREATE TABLE usuario_especialista (
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    especialista_id BIGINT NOT NULL REFERENCES especialista (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, especialista_id)
);

CREATE TABLE politica_cancelacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horas_minimas_cancelacion_paciente INT NOT NULL DEFAULT 24
);

INSERT INTO politica_cancelacion (horas_minimas_cancelacion_paciente) VALUES (24);

CREATE TABLE cita_portal_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT NOT NULL REFERENCES cita (id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expira_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    puede_confirmar BOOLEAN NOT NULL DEFAULT TRUE,
    puede_cancelar BOOLEAN NOT NULL DEFAULT TRUE,
    puede_reprogramar BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cita_portal_cita ON cita_portal_token (cita_id);

CREATE TABLE cita_lista_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES paciente (id),
    especialista_id BIGINT REFERENCES especialista (id),
    sala_id BIGINT REFERENCES sala (id),
    tipo_cita_catalogo_id BIGINT REFERENCES catalogo (id),
    prioridad INT NOT NULL DEFAULT 0,
    estado VARCHAR(40) NOT NULL,
    notas VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atendido_cita_id BIGINT REFERENCES cita (id)
);

CREATE INDEX idx_lista_esp_estado ON cita_lista_espera (estado, especialista_id);

CREATE TABLE cita_vinculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT NOT NULL REFERENCES cita (id) ON DELETE CASCADE,
    tipo_vinculo VARCHAR(40) NOT NULL,
    ref_id BIGINT NOT NULL,
    descripcion VARCHAR(500)
);

CREATE INDEX idx_cita_vinculo_cita ON cita_vinculo (cita_id);

CREATE TABLE paciente_consentimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    version_etiqueta VARCHAR(80) NOT NULL,
    texto_resumen VARCHAR(2000),
    canal VARCHAR(40),
    aceptado_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_user_id BIGINT REFERENCES app_user (id)
);

CREATE INDEX idx_consent_paciente ON paciente_consentimiento (paciente_id);

CREATE TABLE acceso_datos_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_user (id),
    paciente_id BIGINT REFERENCES paciente (id),
    recurso VARCHAR(120) NOT NULL,
    accion VARCHAR(40) NOT NULL,
    ip VARCHAR(64),
    creado_ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_acceso_log_user ON acceso_datos_log (user_id, creado_ts);

CREATE TABLE regla_agenda_recurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurso_tipo VARCHAR(20) NOT NULL,
    recurso_id BIGINT NOT NULL,
    dia_semana SMALLINT,
    franja_inicio TIME,
    franja_fin TIME,
    max_citas_dia INT,
    max_citas_hora INT,
    buffer_antes_min INT NOT NULL DEFAULT 0,
    buffer_despues_min INT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_regla_recurso ON regla_agenda_recurso (recurso_tipo, recurso_id, activo);

CREATE TABLE paciente_metrica (
    paciente_id BIGINT NOT NULL PRIMARY KEY REFERENCES paciente (id) ON DELETE CASCADE,
    no_show_total INT NOT NULL DEFAULT 0,
    no_show_ultima_ts TIMESTAMP WITH TIME ZONE
);
