CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app_role (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE tipo_catalogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE catalogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_catalogo_id BIGINT NOT NULL REFERENCES tipo_catalogo (id),
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    orden INT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSON,
    UNIQUE (tipo_catalogo_id, codigo)
);

CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    telefono VARCHAR(50),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE especialista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL UNIQUE REFERENCES staff (id) ON DELETE CASCADE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE especialista_especialidad (
    especialista_id BIGINT NOT NULL REFERENCES especialista (id) ON DELETE CASCADE,
    catalogo_id BIGINT NOT NULL REFERENCES catalogo (id) ON DELETE CASCADE,
    PRIMARY KEY (especialista_id, catalogo_id)
);

CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    numero_expediente VARCHAR(64) NOT NULL UNIQUE,
    fecha_nacimiento DATE,
    telefono VARCHAR(50),
    notas TEXT,
    capacidades_info TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES paciente (id),
    especialista_id BIGINT NOT NULL REFERENCES especialista (id),
    inicio_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    fin_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_minutos INT NOT NULL DEFAULT 45,
    estado VARCHAR(40) NOT NULL,
    notas TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cita_especialista_inicio ON cita (especialista_id, inicio_ts);
CREATE INDEX idx_cita_paciente_inicio ON cita (paciente_id, inicio_ts);

CREATE TABLE documento_paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    tipo_catalogo_id BIGINT REFERENCES tipo_catalogo (id),
    tipo_documento_catalogo_id BIGINT REFERENCES catalogo (id),
    nombre_archivo VARCHAR(512) NOT NULL,
    mime_type VARCHAR(128),
    ruta_storage VARCHAR(1024) NOT NULL,
    tamano_bytes BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_subida_id BIGINT REFERENCES app_user (id)
);

CREATE TABLE cita_financiero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT NOT NULL UNIQUE REFERENCES cita (id) ON DELETE CASCADE,
    monto_ingreso NUMERIC(19, 2) NOT NULL DEFAULT 0,
    monto_costo NUMERIC(19, 2) NOT NULL DEFAULT 0,
    moneda VARCHAR(3) NOT NULL DEFAULT 'NIO',
    notas TEXT
);

CREATE INDEX idx_cita_financiero_cita ON cita_financiero (cita_id);
