ALTER TABLE app_user ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE app_user ADD COLUMN password_must_change BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app_user ADD COLUMN temporal_password BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE iam_pantalla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    ruta VARCHAR(512),
    orden INT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE iam_pantalla_rol (
    pantalla_id BIGINT NOT NULL REFERENCES iam_pantalla (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app_role (id) ON DELETE CASCADE,
    PRIMARY KEY (pantalla_id, role_id)
);

INSERT INTO iam_pantalla (codigo, nombre, descripcion, ruta, orden, activo) VALUES
    ('INICIO', 'Inicio', 'Panel principal', '/app/pages/inicio.html', 1, TRUE),
    ('GRAFICOS', 'Gráficos', 'Indicadores', '/app/pages/graficos.html', 2, TRUE),
    ('AGENDA', 'Agenda', 'Vista semanal de citas', '/app/pages/agenda.html', 3, TRUE),
    ('CITAS', 'Citas', 'Gestión de citas', '/app/pages/citas.html', 4, TRUE),
    ('PACIENTES', 'Pacientes', 'Expedientes', '/app/pages/pacientes.html', 5, TRUE),
    ('ESPECIALIDADES', 'Especialidades', 'Catálogo', '/app/pages/especialidades.html', 6, TRUE),
    ('ESPECIALISTAS', 'Especialistas', 'Personal médico', '/app/pages/especialistas.html', 7, TRUE),
    ('REPORTES', 'Reportes', 'Exportaciones', '/app/pages/reportes.html', 8, TRUE),
    ('IAM', 'IAM', 'Administración identidad', '/iam/index.html', 9, TRUE);
